practice-for-ch-rails-music-app-long-practice-main/practice-for-ch-rails-music-app-long-practice-main/Music_App/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#show"
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :show, :edit, :create, :destroy]
end

practice-for-ch-rails-music-app-long-practice-main/practice-for-ch-rails-music-app-long-practice-main/Music_App/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

practice-for-ch-rails-music-app-long-practice-main/practice-for-ch-rails-music-app-long-practice-main/Music_App/app/models/band.rb
class Band < ApplicationRecord
end

practice-for-ch-rails-music-app-long-practice-main/practice-for-ch-rails-music-app-long-practice-main/Music_App/app/models/user.rb
class User < ApplicationRecord
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  before_validation :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    if user && user.is_password?(password)
      user
    else
      nil
    end
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  def password=(password)
    @password = password 
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = generate_unique_session_token
    self.save!
    self.session_token
  end

    private
  def generate_unique_session_token
    loop do 
    session_token = SecureRandom::urlsafe_base64
      return session_token unless User.exists?(session_token: session_token)
    end
  end

  def ensure_session_token
    self.session_token ||= generate_unique_session_token
  end
end

practice-for-ch-rails-music-app-long-practice-main/practice-for-ch-rails-music-app-long-practice-main/Music_App/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  private

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!

  end
  def logout!
    current_user.reset_session_token! if current_user #current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end
  def logged_in?
    !!current_user
  end


  def require_logged_out
      redirect_to root_url if current_user
  end

  def require_logged_in
    redirect_to new_session_url if current_user
  end


end

practice-for-ch-rails-music-app-long-practice-main/practice-for-ch-rails-music-app-long-practice-main/Music_App/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_logged_out, only: %i(create new)
  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if user.nil?
      flash.now[:errors] = ["Incorrect username and/or password"]
      render :new
    else
      login!(user)
      redirect_to new_session_url
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

  def new
  end
end

practice-for-ch-rails-music-app-long-practice-main/practice-for-ch-rails-music-app-long-practice-main/Music_App/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
   @user = User.new
  end

  def show 
    @user = User.find_by(params[name: :email])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

practice-for-ch-rails-music-app-long-practice-main/practice-for-ch-rails-music-app-long-practice-main/Music_App/app/helpers/application_helper.rb
module ApplicationHelper
end

practice-for-ch-rails-music-app-long-practice-main/practice-for-ch-rails-music-app-long-practice-main/Music_App/app/helpers/sessions_helper.rb
module SessionsHelper
end

practice-for-ch-rails-music-app-long-practice-main/practice-for-ch-rails-music-app-long-practice-main/Music_App/app/helpers/users_helper.rb
module UsersHelper
end

practice-for-ch-rails-music-app-long-practice-main/practice-for-ch-rails-music-app-long-practice-main/Music_App/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
   <nav class="main-nav">
    <h1><a href="<%= root_url %>" > MusicApp</a></h1>
    <div>
      <% if !logged_in? %>
        <a href="<%= new_session_url %>">Sign in</a>
        <a href="<%= new_user_url%>">Sign up </a>
      <% else %>
        <%= current_user.email %>
          <form action="<%= session_url %>" method="post">
            <input
              type="hidden"
              name="authenticity_token"
              value="<%= form_authenticity_token %>"
            >
            <input type="hidden" name="_method" value="delete">
            <input type="submit" value="Logout">
          </form>
      <% end %>
     </nav>
  <main> 
    <%= yield %>
    </main>
  </body>
</html>

practice-for-ch-rails-music-app-long-practice-main/practice-for-ch-rails-music-app-long-practice-main/Music_App/app/views/users/new.html.erb
<section class="page">
  <div class="centered-box">
    <h1>New User</h1>

   

    <form action="<%= users_url %>" method="post">
      <input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">

      <label for="user_email">Email: </label>
      <input type="text"
        name="user[email]"
        id="user_email"
        value="<%= @user.email %>">
      <br>

      <label for="user_password">Password: </label>
      <input type="password"
        name="user[password]"
        id="user_password"
        value="<%= @user.password %>">
      <br>

      <input type="submit" value="Sign up!">
    </form>
  </div>
</section>

practice-for-ch-rails-music-app-long-practice-main/practice-for-ch-rails-music-app-long-practice-main/Music_App/app/views/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

<%= @user.email %>